=== BehaimITS/TestGIT/bw/CacheUpdate/Schemas/data/Customer360Messages.xsd
<?xml version="1.0" encoding="utf-8" ?><xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://behaimits.com/vectren/bigdata/customer360view/Customer360Messages" xmlns="http://behaimits.com/vectren/bigdata/customer360view/Customer360Messages" elementFormDefault="qualified">
<xs:complexType name="Customer360MessagesItemType"><xs:sequence>
<xs:element name="MSG_SEQUENCE_NO" type="xs:float" minOccurs="0" />
<xs:element name="MSG_TIME" type="xs:dateTime" minOccurs="0" />
<xs:element name="ACCOUNT_NUMBER" type="xs:string" minOccurs="0" />
<xs:element name="MSG_KEY" type="xs:string" minOccurs="0" />
<xs:element name="SOURCE_TUPLE_ID" type="xs:float" minOccurs="0" />
<xs:element name="MSG_DEST" type="xs:string" minOccurs="0" />
<xs:element name="MSG_TEXT" type="xs:string" minOccurs="0" />
</xs:sequence></xs:complexType><xs:element name="Customer360MessagesItem" type="Customer360MessagesItemType" /></xs:schema>

=== BehaimITS/TestGIT/bw/CacheUpdate/Schemas/data/Customer360Messages.xml
<?xml version="1.0" encoding="UTF-8"?>
<p:Customer360MessagesItem xmlns:p="http://behaimits.com/vectren/bigdata/customer360view/Customer360Messages" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://behaimits.com/vectren/bigdata/customer360view/Customer360Messages Customer360Messages.xsd ">
  <p:MSG_SEQUENCE_NO>0.0</p:MSG_SEQUENCE_NO>
  <p:MSG_TIME>2001-12-31T12:00:00</p:MSG_TIME>
  <p:ACCOUNT_NUMBER>p:ACCOUNT_NUMBER</p:ACCOUNT_NUMBER>
  <p:MSG_KEY>p:MSG_KEY</p:MSG_KEY>
  <p:SOURCE_TUPLE_ID>0.0</p:SOURCE_TUPLE_ID>
  <p:MSG_DEST>p:MSG_DEST</p:MSG_DEST>
  <p:MSG_TEXT>p:MSG_TEXT</p:MSG_TEXT>
</p:Customer360MessagesItem>
